CREATE TABLE IF NOT EXISTS USERS (
  USER_ID int(6) NOT NULL,
  FIRST_NAME varchar(20),
  LAST_NAME varchar (20),
  BALANCE decimal(4, 1),
  PHONE varchar(10),
  EMAIL varchar(20),
  PRIMARY KEY (USER_ID)
);CREATE TABLE IF NOT EXISTS ROOMS (
  ROOM_ID INT(6) NOT NULL,
  TOTAL_STATIONS INT(2),
  NAME VARCHAR(20),
  PRIMARY KEY (ROOM_ID)
);CREATE TABLE IF NOT EXISTS Tabs(
  TAB_ID INT(6) NOT NULL,
  SESSION_ID INT(6) NOT NULL,
  PAY_STATUS BIT NOT NULL,
  TOTAL_COST DECIMAL(4,1),
  PRIMARY KEY (TAB_ID),
  FOREIGN KEY (SESSION_ID) REFERENCES SESSIONS(SESSION_ID)
);CREATE TABLE IF NOT EXISTS SESSIONS (
  SESSION_ID INT(6) NOT NULL,
  START_TIME DATETIME DEFAULT GETDATE(),
  END_TIME DATETIME,
  USER_ID INT(6) NOT NULL,
  PRIMARY KEY (SESSION_ID),
  FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);CREATE TABLE IF NOT EXISTS STATIONS (
  STATION_ID INT(6) NOT NULL,
  ROOM_ID INT(6),
  NUM_SEATS INT(1),
  PRIMARY KEY (STATION_ID),
  FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ROOM_ID)
);
