INSERT INTO `USERS` (`USER_ID`, `FIRST_NAME`, `LAST_NAME`, `BALANCE`, `PHONE`,`EMAIL`) VALUES
('1', 'JEAN', 'BELLIVEAU', '5', '1234567890','jb@j.com'),
('2', 'LIZZIE', 'CHAMBERLAIN', '6', '0987654321','ec@e.com');

INSERT INTO ROOMS (ROOM_ID, TOTAL_STATIONS, NAME) VALUES
(1, 13, 'PC LAB');

INSERT INTO SESSIONS (SESSION_ID, START_TIME, END_TIME, USER_ID) VALUES
(1, NOW(), NULL, 1),
(2, NOW(), NOW(), 1),
(3, NOW(), NOW(), 2);

INSERT INTO STATIONS (STATION_ID, ROOM_ID, NUM_SEATS) VALUES
(1, 1, 2),
(2, 1, 1);